### ISSUE TITLE
Integrate git commits and GitHub release

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/manage-changelog#13]
We could integrate git commit, tag and GitHub release into the action, so that the usage would look like:

```yaml
jobs:
  changelog:
    uses: ./.github/workflows/changelog.yml

  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: [ changelog, test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update package version
        run: npm --no-git-tag-version --allow-same-version version ${{ needs.changelog.outputs.next-version }}

      - name: Update changelog
        id: release-changelog
        uses: OpenTermsArchive/changelog-action/release@v0.4.0
        with:
          git-username: "Open Terms Archive Release Bot"
          git-email: "release-bot@opentermsarchive.org"
          additional-files: package.json package-lock.json

      - name: Publish to NPM public repository
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPMJS_ACCESS_TOKEN }}
```
